import type { Metadata } from 'next'
import './globals.css'
import { funnel } from '@/app/ui/fonts'

export const metadata: Metadata = {
  title: 'In Ho (Luke) Seo | Full-stack Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ `${funnel.className} antialiased` }
      >
        { children }
      </body>
    </html>
  )
}
