import type { Metadata } from 'next'
import './globals.css'
import { funnel } from '@/app/ui/fonts'
import localFont from 'next/font/local'


export const metadata: Metadata = {
  title: 'In Ho (Luke) Seo | Full-stack Developer',
  description: 'Generated by create next app',
}

const pretendard = localFont({
  src: '../app/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body
        className={ `${pretendard.variable}` }
      >
        { children }
      </body>
    </html>
  )
}
