import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'


export const metadata: Metadata = {
  title: 'In Ho (Luke) Seo | Full-stack Developer',
  description: 'Generated by create next app',
}

const Interop = localFont({
  src: '../app/fonts/Interop-Regular.woff2',
  display: 'swap',
  weight: '100-900',
  variable: '--font-interop',
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={ `${Interop.variable}` }
      >
        { children }
      </body>
    </html>
  )
}
